[project]
name = "temporaltidesluna"
version = "0.1.0"
description = "GUI for lejaren to compose for Temporal Tides project"
authors = [
    {name = "anstepp",email = "stepp.aaron@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
