[project]
name = "temporaltidesluna"
version = "0.1.0"
description = "GUI for lejaren to compose for Temporal Tides project"
authors = [
    {name = "anstepp",email = "stepp.aaron@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest (>=9.0.3,<10.0.0)",
    "numpy (>=2.4.6,<3.0.0)",
    "scipy (>=1.17.1,<2.0.0)"
]

[tool.pytest]
minversion = "9.0"
addopts = ["-ra", "-q"]
testpaths = [
    "tests",
    "integration",
]

pythonproject = ["/src"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
