name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry' # Enables automatic dependency caching

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Test with pytest
        run: |
          source .venv/bin/activate
          poetry run pytest
